---
env:
  node: true

extends:
  - 'airbnb-base'
  - 'prettier'

plugins:
  - 'prettier'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  func-names: 0
  no-use-before-define: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/prefer-default-export: 0
  prettier/prettier:
    - error
